[tool.black]
line-length = 100

[tool.isort]
known_first_party = ["image_guru_model_inference"]

# required for compatibility with black:
profile = "black"

# To maintain consistency with other settings
line_length = 100

